# Generated by Django 5.0.7 on 2024-08-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_app', '0002_alter_expense_expense_type_alter_expense_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='include_self',
            field=models.BooleanField(default=True),
        ),
    ]
