# Generated by Django 5.0.7 on 2024-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses_app', '0003_expense_include_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpensedetail',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
