# Generated by Django 5.0.7 on 2024-08-02 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Expenses_app', '0004_groupexpensedetail_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('notification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Expenses_app.expense')),
            ],
        ),
    ]
