# Generated by Django 5.0.7 on 2024-08-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensenotification',
            name='one_hour_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensenotification',
            name='twenty_four_hour_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
